doctor_client_portal-master/config/routes.rb
Rails.application.routes.draw do
  authenticated :admin_user do
    root :to => "admin#index", as: :admin_root
  end

  get 'admin/index' => "admin#index"

  get 'admin/new' => "admin#new", as: :patient_infos
  get 'admin/new_medical' => "admin#new_medical_hist", as: :medical_histories
  get 'admin/new_physical' => "admin#new_physical_exam", as: :physical_exams
  get 'admin/new_notes' => "admin#new_note", as: :notes

  post 'admin/new'  => "admin#create"
  post 'admin/new_medical'  => "admin#create_medical_hist"
  post 'admin/new_physical'  => "admin#create_physical_exam"
  post 'admin/new_notes'  => "admin#create_note"

  get 'admin/:user_id' => "admin#show", as: :show_user

  get 'guest/:user_id/show_patient_info' => "guest#show_patient_info", as: :show_patient
  get 'guest/:user_id/show_medical_hist' => "guest#show_medical_hist", as: :show_medical
  get 'guest/:user_id/show_physical_exam' => "guest#show_physical_exam", as: :show_physical
  get 'guest/:user_id/show_note' => "guest#show_note", as: :show_note

  get 'admin/:user_id/edit' => "admin#edit", as: :edit_patient
  get 'admin/:user_id/edit_medical' => "admin#edit_medical_hist", as: :edit_medical
  get 'admin/:user_id/edit_physical' => "admin#edit_physical_exam", as: :edit_physical
  get 'admin/:user_id/edit_note' => "admin#edit_note", as: :edit_note

  patch 'admin/:user_id/update' => "admin#update"
  patch 'admin/:user_id/update_medical' => "admin#update_medical_hist"
  patch 'admin/:user_id/update_physical' => "admin#update_physical_exam"
  patch 'admin/:user_id/update_note' => "admin#update_note"

  delete 'admin/:id'  => "admin#destroy", as: :delete

  devise_for :users
  get 'welcome/index'

  root to: "welcome#index"

end

doctor_client_portal-master/app/models/medical_history.rb
class MedicalHistory < ActiveRecord::Base
  belongs_to :user
end

doctor_client_portal-master/app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

doctor_client_portal-master/app/models/patient_info.rb
class PatientInfo < ActiveRecord::Base
  belongs_to :user
end

doctor_client_portal-master/app/models/physical_exam.rb
class PhysicalExam < ActiveRecord::Base
  belongs_to :user
end

doctor_client_portal-master/app/models/user.rb
class User < ActiveRecord::Base
 has_many :patient_infos, dependent: :destroy
 has_many :medical_histories, dependent: :destroy
 has_many :notes, dependent: :destroy
 has_many :physical_exams, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

doctor_client_portal-master/app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :authenticate_user!
#protect_from_forgery prepend: true
 #before_action :authenticate_user!
 before_action :authorize_admin

 def authorize_admin
 if current_user.admin
   #redirect_to admin_index_path
 else
   
   redirect_to welcome_index_path
 end
 end
#Index action list patient name with links
  def index

    @patient_infos = PatientInfo.all

  end


#New action

#new action PatientInfo
  def new
    @patient_infos = PatientInfo.new
  end

#new action MedicalHistory
  def new_medical_hist
    @medical_histories = MedicalHistory.new
    render "new_medical"
  end

#new action PhysicalExam
  def new_physical_exam
    @physical_exams = PhysicalExam.new
    render "new_physical"
  end

#new action Note
  def new_note
    @notes = Note.new
    render "new_notes"
  end


#Action create

#create action PatientInfo

def create
    @patient_infos = PatientInfo.new(params.require(:patient_info).permit(:user_id, :name, :age, :gender, :address, :contact, :health_insurance, :primary_doctor))

    if @patient_infos.save
      redirect_to medical_histories_path
    else
      render :new
  end
end

#create action Medical History
def create_medical_hist
   @medical_histories = MedicalHistory.new(params.require(:medical_history).permit(:user_id, :cardio_diagnostic, :cardio_secondary, :clinical_diagnostic, :clinical_secondary, :cardio_medication, :secondary_medication, :related_medication))

    if @medical_histories.save
      redirect_to physical_exams_path
    else
      render :new_medical_hist
  end
end

#create action Physical Exam
def create_physical_exam
  @physical_exams = PhysicalExam.new(params.require(:physical_exam).permit(:user_id, :pulse, :systolic_pressure, :diastolic_pressure, :height, :weight))

    if @physical_exams.save
      redirect_to notes_path
    else
      render :new_physical_exam
  end
end

#create action Note
def create_note
  @notes = Note.new(params.require(:note).permit(:user_id, :text, :date))

   if @notes.save
    redirect_to show_user_path
   else
    render :new_note
  end
end

    #Show action
  def show

    @patient_infos = PatientInfo.where(user_id: params[:user_id]).first
    @medical_histories = MedicalHistory.where(user_id: params[:user_id]).first
    @physical_exams = PhysicalExam.where(user_id: params[:user_id]).first
    @notes = Note.where(user_id: params[:user_id]).first

  end


#Edit action
#edit patient info
  def edit
    @patient_infos = PatientInfo.where(user_id: params[:user_id]).first
  end

#edit medical histories
 def edit_medical_hist
  @medical_histories = MedicalHistory.where(user_id: params[:user_id]).first
 end

#edit physical exams
def edit_physical_exam
  @physical_exams = PhysicalExam.where(user_id: params[:user_id]).first
end

#edit note
def edit_note
  @notes = Note.where(user_id: params[:user_id]).first
end


#Update action

#Update Patient Info action
def update
  @patient_infos = PatientInfo.where(user_id: params[:user_id]).first

  if @patient_infos.update_attributes(params.permit(:user_id, :name, :age, :gender, :address, :contact, :health_insurance, :primary_doctor))
    redirect_to show_user_path
  else
    render :edit
  end
end

#Update Medical History action
def update_medical_hist
  @medical_histories = MedicalHistory.where(user_id: params[:user_id]).first

  if @medical_histories.update_attributes(params.permit(:user_id, :cardio_diagnostic, :cardio_secondary, :clinical_diagnostic, :clinical_secondary, :cardio_medication, :secondary_medication, :related_medication))
    redirect_to show_user_path
  else
    render :edit_medical_hist
end
end

#Update Physical Exam
def update_physical_exam
  @physical_exams = PhysicalExam.where(user_id: params[:user_id]).first

  if @physical_exams.update_attributes(params.permit(:user_id, :pulse, :systolic_pressure, :diastolic_pressure, :height, :weight))
    redirect_to show_user_path
  else
    render :edit_physical_exam
  end
end

#Update Note
def update_note
  @notes = Note.where(user_id: params[:user_id]).first

  if @notes.update_attributes(params.permit(:user_id, :text, :date))
    redirect_to show_user_path
  else
    render :edit_note
  end
end



#Destroy action
  def destroy
    @user = User.where(id: params[:id]).first
    if @user.present?
    @user.destroy
  end
    redirect_to admin_index_path
end
end

doctor_client_portal-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead


  protect_from_forgery with: :exception

  def set_current_user
    @current_user = User.current
  if @current_user.admin?
    redirect_to admin_index_path
  end

end
end

doctor_client_portal-master/app/controllers/guest_controller.rb
class GuestController < ApplicationController

before_action :authenticate_user!




  def show_patient_info

    @patient_infos = PatientInfo.where(user_id: params[:user_id]).first

  end


  def show_medical_hist

    @medical_histories = MedicalHistory.where(user_id: params[:user_id]).first

  end

  def show_physical_exam

    @physical_exams = PhysicalExam.where(user_id: params[:user_id]).first

  end

  def show_note

    @notes = Note.where(user_id: params[:user_id]).first

  end



end

doctor_client_portal-master/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index

    @patient_infos = PatientInfo.where(user_id: current_user.id)
  end
end

doctor_client_portal-master/app/helpers/admin_helper.rb
module AdminHelper
end

doctor_client_portal-master/app/helpers/application_helper.rb
module ApplicationHelper
end

doctor_client_portal-master/app/helpers/guest_helper.rb
module GuestHelper
end

doctor_client_portal-master/app/helpers/welcome_helper.rb
module WelcomeHelper
end

doctor_client_portal-master/app/views/admin/destroy.html.erb
<h1>Admin#destroy</h1>
<p>Find me in app/views/admin/destroy.html.erb</p>

doctor_client_portal-master/app/views/admin/edit.html.erb
<div class = "patient">
<h1>Edit Patient Info!</h1>

<%= form_tag("/admin/#{@patient_infos.user_id}/update", method: "patch")  do  %>

    <div>
        <%= label_tag :name %>
        <%= text_field_tag :name, @patient_infos.name %>
    </div>

    <div>
        <%= label_tag :age %>
        <%= text_field_tag :age, @patient_infos.age %>
    </div>

    <div>
        <%= label_tag :gender %>
        <%= text_field_tag :gender, @patient_infos.gender %>
    </div>

    <div>
        <%= label_tag :address %>
        <%= text_field_tag :address, @patient_infos.address %>
    </div>

    <div>
        <%= label_tag :contact %>
        <%= text_field_tag :contact, @patient_infos.contact %>
    </div>

    <div>
        <%= label_tag :health_insurance %>
        <%= text_field_tag :health_insurance, @patient_infos.health_insurance %>
    </div>

    <div>
        <%= label_tag :primary_doctor %>
        <%= text_field_tag :primary_doctor, @patient_infos.primary_doctor%>
    </div>
</br>
    <%= submit_tag "Submit these changes!" %>

<% end %>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Back", show_user_path %></button>
</br></br>
<button type="button" class="btn btn-default">
<%= link_to "Back to Patient list!", admin_index_path %></button>
</br>
</div>

doctor_client_portal-master/app/views/admin/edit_medical_hist.html.erb
<div class = "patient">

<h1>Edit Medical History!</h1>

<%= form_tag("/admin/#{@medical_histories.user_id}/update_medical", method: "patch")  do  %>

    <div>
        <%= label_tag :cardio_diagnostic %>
        <%= text_field_tag :cardio_diagnostic, @medical_histories.cardio_diagnostic %>
    </div>

    <div>
        <%= label_tag :cardio_secondary %>
        <%= text_field_tag :cardio_secondary, @medical_histories.cardio_secondary %>
    </div>

    <div>
        <%= label_tag :clinical_diagnostic %>
        <%= text_field_tag :clinical_diagnostic, @medical_histories.clinical_diagnostic %>
    </div>

    <div>
        <%= label_tag :clinical_secondary %>
        <%= text_field_tag :clinical_secondary, @medical_histories.clinical_secondary %>
    </div>

    <div>
        <%= label_tag :cardio_medication %>
        <%= text_field_tag :cardio_medication, @medical_histories.cardio_medication %>
    </div>

    <div>
        <%= label_tag :secondary_medication %>
        <%= text_field_tag :secondary_medication, @medical_histories.secondary_medication %>
    </div>

    <div>
        <%= label_tag :related_medication %>
        <%= text_field_tag :related_medication, @medical_histories.related_medication%>
    </div>
</br>
    <%= submit_tag "Submit these changes!" %>

<% end %>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Back", show_user_path %></button>

</br>
<button type="button" class="btn btn-default">
<%= link_to "Back to the list!", admin_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/edit_note.html.erb
<div class = "patient">
<h1>Edit Medical Notes!</h1>

<%= form_tag("/admin/#{@notes.user_id}/update_note", method: "patch")  do  %>

    <div>
        <%= label_tag :text %>
        <%= text_field_tag :text, @notes.text %>
    </div>

    <div>
        <%= label_tag :date %>
        <%= text_field_tag :date, @notes.date %>
    </div>



    <%= submit_tag "Submit these changes!" %>

<% end %>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Back", show_user_path %></button>

</br>
<button type="button" class="btn btn-default">
<%= link_to "Back to the list!", admin_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/edit_physical_exam.html.erb
<div class = "patient">
<h1>Edit Physical Exam!</h1>

<%= form_tag("/admin/#{@physical_exams.user_id}/update_physical", method: "patch")  do  %>

    <div>
        <%= label_tag :pulse %>
        <%= text_field_tag :pulse, @physical_exams.pulse %>
    </div>

    <div>
        <%= label_tag :systolic_pressure %>
        <%= text_field_tag :systolic_pressure, @physical_exams.systolic_pressure %>
    </div>

    <div>
        <%= label_tag :diastolic_pressure %>
        <%= text_field_tag :diastolic_pressure, @physical_exams.diastolic_pressure %>
    </div>

    <div>
        <%= label_tag :height %>
        <%= text_field_tag :height, @physical_exams.height %>
    </div>

    <div>
        <%= label_tag :weight %>
        <%= text_field_tag :weight, @physical_exams.weight %>
    </div>


    <%= submit_tag "Submit these changes!" %>

<% end %>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Back", show_user_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Back to the list!", admin_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/index.html.erb
<div class = "patient">

<h1>Patient List</h1>


<ul>
    <% @patient_infos.each do |patient_info| %>
        <a href="/admin/<%= patient_info.user_id %>" >
        <li>
            <strong> <%= patient_info.name%></strong>
        </li>
</a>

    <% end %>
</ul>

</br>

</br><button type="button" class="btn btn-default">
<%= link_to "Back", welcome_index_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Add a new Patient", patient_infos_path %></button>
</div>

doctor_client_portal-master/app/views/admin/new.html.erb
<div class = "patient">



<h1>Add a new Patient!</h1>
<%= form_for @patient_infos do |f| %>
<h2>Patient Info:<h2>

   <div>
      <%= f.label :user_id%>
      <%= f.text_field :user_id%>
   </div>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :age %>
        <%= f.text_field :age %>
    </div>

    <div>
        <%= f.label :gender %>
        <%= f.text_field :gender %>
    </div>

    <div>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </div>

    <div>
        <%= f.label :contact %>
        <%= f.text_field :contact %>
    </div>

    <div>
        <%= f.label :health_insurance %>
        <%= f.text_field :health_insurance%>
    </div>

    <div>
        <%= f.label :primary_doctor %>
        <%= f.text_field :primary_doctor %>
    </div>

    <%= f.submit "Add new Patient!" %>


<% end %>
</br></br>
<button type="button" class="btn btn-default">
<%= link_to "Add Medical History!", medical_histories_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Menu", welcome_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/new_medical.html.erb
<div class = "patient">
<h1>Add a new Patient!</h1>
<%= form_for @medical_histories do |f| %>
<h2>Medical History:<h2>

   <div>
      <%= f.label :user_id %>
      <%= f.text_field :user_id %>
   </div>


    <div>
        <%= f.label :cardio_diagnostic %>
        <%= f.text_field :cardio_diagnostic %>
    </div>

    <div>
        <%= f.label :cardio_secondary %>
        <%= f.text_field :cardio_secondary %>
    </div>

    <div>
        <%= f.label :clinical_diagnostic %>
        <%= f.text_field :clinical_diagnostic %>
    </div>

    <div>
        <%= f.label :clinical_secondary %>
        <%= f.text_field :clinical_secondary %>
    </div>

    <div>
        <%= f.label :cardio_medication %>
        <%= f.text_field :cardio_medication %>
    </div>

    <div>
        <%= f.label :secondary_medication %>
        <%= f.text_field :secondary_medication%>
    </div>

    <div>
        <%= f.label :related_medication %>
        <%= f.text_field :related_medication %>
    </div>

    <%= f.submit "Save!" %>


<% end %>
</br></br>
<button type="button" class="btn btn-default">
<%= link_to "Add Physical Exam!", physical_exams_path %></button>
</BR>
<button type="button" class="btn btn-default">
<%= link_to "Menu", welcome_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/new_notes.html.erb
<div class = "patient">
<h1>Add a new Patient!  </h1>
<%= form_for @notes do |f| %>
<h2>Medical Notes:<h2>

   <div>
      <%= f.label :user_id %>
      <%= f.text_field :user_id %>
   </div>


    <div>
        <%= f.label :date %> (yyyy/mm/dd)
        <%= f.text_field :date %>
    </div>

    <div>
        <%= f.label :text %>
        <%= f.text_field :text %>
    </div>



    <%= f.submit "Save!" %>


<% end %>
</br></br>

<button type="button" class="btn btn-default">
<%= link_to "Menu", welcome_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/new_physical.html.erb
<div class = "patient">

<h1>Add a new Patient!</h1>
<%= form_for @physical_exams do |f| %>
<h2>Physical Exam:<h2>
    <div>
        <%= f.label :user_id%>
        <%= f.text_field :user_id %>
    </div>

    <div>
        <%= f.label :pulse%>
        <%= f.text_field :pulse %>
    </div>

    <div>
        <%= f.label :systolic_pressure %>
        <%= f.text_field :systolic_pressure %>
    </div>

    <div>
        <%= f.label :diastolic_pressure %>
        <%= f.text_field :diastolic_pressure %>
    </div>

    <div>
        <%= f.label :height%>
        <%= f.text_field :height %>
    </div>

    <div>
        <%= f.label :weight %>
        <%= f.text_field :weight%>
    </div>



    <%= f.submit "Save" %>

<% end %>

</br></br><button type="button" class="btn btn-default">
<%= link_to "Add Note!", notes_path %></button>

</br><button type="button" class="btn btn-default">
<%= link_to "Menu", welcome_index_path %></button>
</div>

doctor_client_portal-master/app/views/admin/show.html.erb
<div class = "patient">

<h1> <%= @patient_infos.name %> </h1>
 <ul>
   <li>Age: <%= @patient_infos.age%> </li>
   <li>Gender: <%= @patient_infos.gender%> </li>
   <li>Address: <%= @patient_infos.address %></li>
   <li>Phone: <%= @patient_infos.contact %></li>
   <li>Health Insurance: <%= @patient_infos.health_insurance %></li>
   <li>Primary Doctor: <%= @patient_infos.primary_doctor %></li>
 </ul>

<h2>Medical History</h2>
  <ul>
     <li>Cardio Diagnostic: <%= @medical_histories.cardio_diagnostic%>, <%= @medical_histories.cardio_secondary%></li>
     <li>Clinical Diagnostic: <%= @medical_histories.clinical_diagnostic%>, <%= @medical_histories.clinical_secondary%></li>
     <li>Medications: <%= @medical_histories.cardio_medication%>, <%= @medical_histories.secondary_medication%>, <%= @medical_histories.related_medication%></li>

  </ul>

<h3>Physical Exam</h3>
  <ul>
    <li>Pulse: <%= @physical_exams.pulse%> per minute.</li>
    <li>Blood Pressure: <%= @physical_exams.systolic_pressure%> x <%= @physical_exams.diastolic_pressure%> mmHg.</li>
    <li>Height: <%= @physical_exams.height%>.</li>
    <li>Weight: <%= @physical_exams.weight%> lbs.</li>

  </ul>

<h4>Doctor Notes</h4>
<div>
  <div>Date: <%= @notes.date %> - <%= @notes.text%> - !!!END!!!</div>
</div>

</br></br><button type="button" class="btn btn-default">
<%= link_to "Back to the list!", admin_index_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Menu", welcome_index_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Edit Patient Info", edit_patient_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Edit Medical History", edit_medical_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Edit Physical Rxam", edit_physical_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Edit Medical Notes", edit_note_path %></button>
</br>
<button type="button" class="btn btn-default">
<%= link_to "Delete this Patient!", show_user_path, method: :delete, data: { confirm: "Are you sure you want to delete Patient?"} %></button>
</div>

doctor_client_portal-master/app/views/guest/show_medical_hist.html.erb
<div class ="patient">


<h1>Medical History</h1>
  <ul>
     <li>Cardio Diagnostic: <%= @medical_histories.cardio_diagnostic%>, <%= @medical_histories.cardio_secondary%></li>
     <li>Clinical Diagnostic: <%= @medical_histories.clinical_diagnostic%>, <%= @medical_histories.clinical_secondary%></li>
     <li>Medications: <%= @medical_histories.cardio_medication%>, <%= @medical_histories.secondary_medication%>, <%= @medical_histories.related_medication%></li>

  </ul>


</br></br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Physical Exam", show_physical_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Medical Notes", show_note_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Back", show_patient_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Menu", welcome_index_path %></button>
</br>

</div>

doctor_client_portal-master/app/views/guest/show_note.html.erb
<div class ="patient">



<h1>Doctor Notes</h1>
<div>
  <div>Date: <%= @notes.date %> - <%= @notes.text%> - !!!END!!!</div>
</div>


</br></br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Back", show_physical_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Menu", welcome_index_path %></button>
</br>
</div>

doctor_client_portal-master/app/views/guest/show_patient_info.html.erb
<div class ="patient">


<h1> <%= @patient_infos.name %> </h1>
 <ul>
   <li>Age: <%= @patient_infos.age%> </li>
   <li>Gender: <%= @patient_infos.gender%> </li>
   <li>Address: <%= @patient_infos.address %></li>
   <li>Phone: <%= @patient_infos.contact %></li>
   <li>Health Insurance: <%= @patient_infos.health_insurance %></li>
   <li>Primary Doctor: <%= @patient_infos.primary_doctor %></li>
 </ul>


</br></br>


<button type="button" class="btn btn-default btn-md ">
<%= link_to "Medical History", show_medical_path%></button>
</br></br>
<button type="button" class="btn btn-default btn-md">
<%= link_to "Physical Exam", show_physical_path%></button>
</br></br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Medical Notes", show_note_path%></button>
</br></br>


<button type="button" class="btn btn-default btn-md">
<%= link_to "Menu", welcome_index_path %></button>
</br>
</div>

doctor_client_portal-master/app/views/guest/show_physical_exam.html.erb
<div class ="patient">






<h1>Physical Exam</h1>
  <ul>
    <li>Pulse: <%= @physical_exams.pulse%> per minute.</li>
    <li>Blood Pressure: <%= @physical_exams.systolic_pressure%> x <%= @physical_exams.diastolic_pressure%> mmHg.</li>
    <li>Height: <%= @physical_exams.height%>.</li>
    <li>Weight: <%= @physical_exams.weight%> lbs.</li>

  </ul>

</br></br>


<button type="button" class="btn btn-default btn-md ">
<%= link_to "Medical Notes", show_note_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Back", show_medical_path%></button>
</br>
<button type="button" class="btn btn-default btn-md ">
<%= link_to "Menu", welcome_index_path %></button>
</br>


</div>

doctor_client_portal-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Doctor-Client Portal</title>

    <!-- Bootstrap -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="/main.css">
  </head>
  <body class = "body">

    <nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">


        <img alt="Brand" src="http://i.imgur.com/BRHbQSr.jpg?1">
      </a>

      

<p class="navbar-text navbar-right"> <%= notice %>  <%= alert %>  <% if user_signed_in? %>
     Signed in as <%= current_user.email %>(#<%= current_user.id%>)
    <button type="button" class="btn btn-default btn-sm"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></button>
 <% else %>
    <button type="button" class="btn btn-default btn-sm"><%= link_to 'Register', new_user_registration_path %></button> or <button type="button" class="btn btn-default btn-sm"><%= link_to 'Sign in', new_user_session_path %></button>
 <% end %></p>


  </div>
</nav>













<%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>

doctor_client_portal-master/app/views/welcome/index.html.erb
<div class ="patient">
<h1 id = "welcome_h1">Welcome,</h1>
</br>

<ul id="patient_info">
    <% @patient_infos.each do |patient_info| %>
        <a href="/guest/<%= patient_info.user_id %>/show_patient_info" >
        <li>
            <strong> <%= patient_info.name%></strong>
        </li>
</a>

    <% end %>
</ul>


</br><button type="button" class="btn btn-default">
<%= link_to "Edit Account", edit_user_registration_path %>
</button>
</br><button type="button" class="btn btn-default btn-md ">
<%if current_user.admin?%>
<%= link_to "Patient List", admin_index_path %>
<%end%></button>   
</br>
</div>